### ISSUE TITLE
Need a button to purchase options

### ISSUE THREAD

**Issue by jacobmort** [PermanentLoss/permanentloss#19]
Interact directly w/uniswap contract?
Redirect to the uniswap pool?

**Comment by andrekorol** [comment]
@ubien Users are supposed to buy both the selected put and call options, correct? Preferably in a single transaction?

**Comment by jacobmort** [comment]
@andrekorol Yup exactly.  I think the PUT option has the most value (if ETH price moons I'm not caring about IL as much) so being able to purchase just one side would be good too.

**Comment by andrekorol** [comment]
So maybe something like a "add to cart" feature would be ideal. Users can either by both or just one, at their choice. And if they choose to buy both PUT and CALL, it should be done in a single transaction so there's less friction to use our interface.

**Comment by andrekorol** [comment]
Implemented in #45
