### ISSUE TITLE
Improve Layout

### ISSUE THREAD

**Issue by jacobmort** [PermanentLoss/permanentloss#22]
graph could be bigger, calculations could be aligned better

**Comment by andrekorol** [comment]
The "/" route component will need some improvements now that it's wrapped in a Bootstrap container. I tried but couldn't figure out how to have the Container component fill the whole viewport vertically and horizontally. I also couldn't center the inner components (Rows) through Bootstrap...

**Comment by jacobmort** [comment]
Alignment & spacing are wack but I made some progress Bootstrapping things

<img width="1148" alt="Screen Shot 2020-10-19 at 10 52 22 PM" src="https://user-images.githubusercontent.com/361696/96545828-ff55be80-125d-11eb-9545-cf5b12cb2ba8.png">

Edit: Just noticed the negative naked projected which shouldn't be possible -- looks like it's labelled wrong and I deleted a row.  Fixing.

**Comment by andrekorol** [comment]
> Alignment & spacing are wack but I made some progress Bootstrapping things
> 

Woah, it looks WAY better now! 😱

**Comment by jacobmort** [comment]
Thanks!  I'll reassign myself when I get time to pick this back up
