### ISSUE TITLE
Faq page looks weird on Netlify deployment

### ISSUE THREAD

**Issue by andrekorol** [PermanentLoss/permanentloss#42]
Maybe wrapping the Faq component in Bootstrap's Col and Row will fix the issue.

**Comment by andrekorol** [comment]
Still not working: [https://deploy-preview-43--stoic-noether-907ad0.netlify.app/faq](https://deploy-preview-43--stoic-noether-907ad0.netlify.app/faq)

@ubien if we commit and push changes to the [fix-faq](https://github.com/PermanentLoss/permanentloss/tree/fix-faq) branch, it gets automatically added to the #43 PR.

**Comment by jacobmort** [comment]
Ok thanks for trying I'll take a look

**Comment by jacobmort** [comment]
Implemented Bootstrap accordion which looks better.  Never figured why `styled-component` was applying these had to override:
<img width="1781" alt="Screen Shot 2020-10-19 at 10 07 19 PM" src="https://user-images.githubusercontent.com/361696/96542751-9b2ffc00-1257-11eb-8b6e-722f7abcdc2f.png">
