### ISSUE TITLE
Add Wutang Financial meme?

### ISSUE THREAD

**Issue by jacobmort** [PermanentLoss/permanentloss#52]
Is there any place we can sneak this in?
![Bh69r_lCUAAqaRJ](https://user-images.githubusercontent.com/361696/96650238-52c01f00-12e7-11eb-8bbd-19cc570242e2.jpg)

**Comment by andrekorol** [comment]
I think we could put it in the faq page lol
Either by just plainly placing it there, or hiding it in a "One more tip" button as an easter-egg 😂
