### ISSUE TITLE
Hide Connect Wallet button for now?

### ISSUE THREAD

**Issue by jacobmort** [PermanentLoss/permanentloss#55]
Don't think we're using it for anything currently?

**Comment by andrekorol** [comment]
Only if users want to use it as their provider, but yes, other than that, it currently has no use.

It's only needed on the `sell` route, where I would implement the feature that would allow users to deposit collateral so they can mint oTokens and then sell them.

I've read that ["Only about 10% of options are exercised, 60% are traded (closed) out, and 30% expire worthlessly."](https://www.investopedia.com/options-basics-tutorial-4583012#how-options-work).

So I think it would be nice to allow users to act as both options buyers and writers (sellers) on the PermanentLoss platform.

**Comment by andrekorol** [comment]
With react-router v6 (which we're already using the beta version of) it's easy to know on which route we're at, so I think we can hide it on the main and faq pages for now. They're also the only routes currently listed on the Navbar, so users probably wouldn't complain about a hidden Connect Wallet button for now.
