### ISSUE TITLE
Intermittent Etherscan Error

### ISSUE THREAD

**Issue by jacobmort** [PermanentLoss/permanentloss#57]
On ~10% of page loads I get this error and not all the graph points load.  Might only be a problem on localhost can't remember seeing it in prod.

<img width="1773" alt="Screen Shot 2020-10-21 at 10 20 42 PM" src="https://user-images.githubusercontent.com/361696/96828061-bf244680-13eb-11eb-8269-cdd683145d98.png">

**Comment by andrekorol** [comment]
I get the same thing on my console. Wanna try switching the default provider?
I'll try to make it work with Infura and Alchemy, whichever works first, we can choose to use for now.

**Comment by andrekorol** [comment]
@ubien I tried using Infura as the web3Provider, but then all calls to [`optionMarket.getEthToTokenInputPrice`](https://github.com/PermanentLoss/permanentloss/blob/958fc463b54b90e6f9dac59d6df9325f968cb659/interface/packages/react-app/src/components/OptionsILGraph/utils.js#L106) would revert.

**Comment by andrekorol** [comment]
BTW, I also noticed that the error doesn't show up on the Netlify deployment. My guess is it automatically sets the CORS header, or Etherscan doesn't accept requests from `localhost` as the origin.

**Comment by andrekorol** [comment]
As for why the other providers revert on that contract call, I still have no idea, and would really like to know why 😅

**Comment by andrekorol** [comment]
My first line of PHP ever, and it wasn't printing `hello world`, yay /s
